language: android
android:
  components:
    - build-tools-19.0.3

before_install:
 - chmod +x gradlew
 
install:
  - gradle wrapper --gradle-version 3.5.0

script:
    - ./gradlew testDevelopmentDebug
