language: android
jdk: oraclejdk7

before_script:
- git config --global core.autoclrf false

android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.0
  - android-23
  - extra-android-m2repository
script: ./gradlew -PdisablePreDex build
