language: android
dist: trusty
android:
  components:
    - tools
    - build-tools-19.1.0
    - android-19
    - platform-tools
before_script:
  - git config --global core.autocrlf false
  - gradle wrapper --gradle-version 5.4.1

licenses:
  - '.+'
